config/routes.rb
Arv2::Application.routes.draw do
  resources :feriados

  resources :goals

  resources :parroquia

  resources :municipios

  resources :estados

  devise_for :users, :controllers => { :passwords => "users/passwords", :sessions => "users/sessions" }
  scope "/admin" do
    resources :users
  end  

  namespace :ventas do 
    resources :seguimientos
  end

  namespace :ventas do 
    resources :presupuestos do
      collection do
        get 'clientes'
        get 'productos'
        get "print/:id" => 'presupuestos#printing', :as => :print
        get "convenio/:id" => 'presupuestos#convenio', :as => :convenio        
      end
    end
  end

  namespace :ventas do 
    resources :clientes do
      collection do
        get "migrate"
        get "print/:id" => 'clientes#printing', :as => :print
      end
    end 
  end

  root :to => 'home#index'

  get "/intranet" => 'intranet#index', :as => :intranet

  get "/cuenta" => 'cuenta#index', :as => :cuenta
  post "/cuenta/show" => 'cuenta#show', :as => :show_cuenta

  get "/informe" => 'informe#index', :as => :informe
  post "/informe/show" => 'informe#show', :as => :show_informe

  get "/productos" => 'productos#index', :as => :productos
  post "/productos/show" => 'productos#show', :as => :show_productos

  get "/garantia" => 'garantia#index', :as => :garantia
  post "/garantia/show" => 'garantia#show', :as => :show_garantia

  match '/historia', :to => 'historia#index'
  match '/contacto', :to => 'contacto#index'  

  match '/servicios', :to => 'servicios#index'

  get "/cobranzas" => 'cobranzas#index', :as => :cobranzas
  get "/cobranzas/historico/:fac_num" => 'cobranzas#historico', :as => :historico_cobranzas_by_factura
  get "/cobranzas/historico" => 'cobranzas#historico', :as => :historico_cobranzas
  post "/cobranzas/show" => 'cobranzas#show', :as => :show_cobranzas
  post "/cobranzas/send_sms" => 'cobranzas#send_sms', :as => :send_sms_cobranzas
  post "/cobranzas/update" => 'cobranzas#update', :as => :update_cobranzas
  get "/cobranzas/experiencias" => 'cobranzas#experiencias', :as => :experiencias_cobranzas
  post "/cobranzas/experiencias" => 'cobranzas#experiencias', :as => :experiencias_cobranzas
  get "/cobranzas/cuenta/:co_cli" => 'cobranzas#cuenta', :as => :cuenta_cobranzas

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
  
end

app/models/cobranza.rb
module Cobranza
  def self.table_name_prefix
    ''
  end
end

app/models/cobranza/carta.rb
class Cobranza::Carta < ActiveRecord::Base
  # establish_connection Rails.env
  self.table_name = 'cartas'
  attr_accessible :co_zon, :co_cli, :entregado

  after_initialize :init

  validates :co_zon, :presence => true
  validates :co_cli, :presence => true

  belongs_to :zona, {:foreign_key => 'co_zon', :primary_key => 'co_zon', :class_name => "Profit::Zona"}
  belongs_to :cliente, {:foreign_key => 'co_cli', :primary_key => 'co_cli', :class_name => "Profit::Cliente"}

  validate :exist_cliente
 
  def exist_cliente
    errors.add(:co_cli) unless Profit::Cliente.find_by_co_cli(self.co_cli)
  end

  def init
    self.entregado = Time.now
  end

  def to_string
    self.co_zon
  end

end

app/models/cobranza/experiencia.rb
class Cobranza::Experiencia < ActiveRecord::Base
  # establish_connection Rails.env
  self.table_name = 'experiencia'
  attr_accessible :desde, :resultado

  before_save :calcular_experiencias

  validates :desde, :presence => true

  def self.calcular_experiencias(el_limit, el_offset)
    archivo = "experiencia" + Time.now.strftime("%Y-%m-%d") + ".csv"
    dir_file = "public/uploads/" + archivo
    file = File.open(dir_file, 'a')

    facturas = Profit::Factura.all_facturas.includes(:cliente).limit(el_limit).offset(el_offset)
    facturas.each_with_index do |f, i|
      f.generar_resumen Time.now
      line = [f.cliente.co_cli, f.cliente.cli_des, "", f.cliente.telefonos, "", "", f.nro_doc_cfxg, f.fec_emis.strftime("%d/%m/%Y"), f.monto_total, f.pago_mensual, f.count_giros, f.fecha_cancelacion.nil? ? '' : f.fecha_cancelacion.strftime("%d/%m/%Y"), f.experiencia].join("\t") unless f.detalle_giros.nil?
      file.puts line
      GC.start if (i % 1000) == 0
    end

    # exp = Cobranza::Experiencia.new
    # exp.desde = Date.today
    # exp.resultado = archivo 
    # exp.save
    # exp
    file.close
    true
  end

  def to_string
    self.desde
  end

end

app/models/cobranza/notificacion.rb
class Cobranza::Notificacion < ActiveRecord::Base
  # establish_connection Rails.env
  self.table_name =  'notificaciones'
  attr_accessible :mes_desde, :mes_hasta, :fecha, :resultado




end

app/models/cobranza/opcion.rb
class Cobranza::Opcion < ActiveRecord::Base
  # establish_connection Rails.env
  self.table_name =  'opciones'
  # attr_accessible :title, :body
end

app/models/cobranza/telefono.rb
class Cobranza::Telefono < ActiveRecord::Base
  # establish_connection Rails.env
  # attr_accessible :title, :body
end

app/controllers/cobranzas_controller.rb
class CobranzasController < ApplicationController
  layout 'intranet'
  before_filter :authenticate_user!


  caches_action :index, :expires_in => 1.day

  def index
    @factura = Profit::Factura.new
    @factura.co_cli = ''
    @facturas = nil
    combos
  end

  def show
    @factura = Profit::Factura.new
    @factura.co_cli = ''

    co_cli = params[:profit_factura][:co_cli]
    dias_desde = params[:dias_vencidos_desde]
    dias_hasta = params[:dias_vencidos_hasta]
    giros_vencidos_desde = params[:giros_vencidos_desde]
    giros_vencidos_hasta = params[:giros_vencidos_hasta]
    co_lin = params[:co_lin]
    co_ven = params[:co_ven]
    co_zon = params[:co_zon]
    @ven_desde = params[:vencidos_desde].first
    @ven_hasta = params[:vencidos_hasta].first  
    plazo_pago = params[:plazo_pago].first
    telefono = params[:telefono].first
    @sin_seguimientos_recientes = params[:recientes].nil? ? false : true
    @sin_pagos_recientes = params[:sin_pagos_recientes].nil? ? false : true



    if !co_cli.empty?
      logger.debug "co_cli"
      @facturas = Profit::Factura.by_cliente co_cli
    elsif dias_desde.to_i >= 0 and dias_hasta.to_i > 0 and dias_desde.to_i <= dias_hasta.to_i
      logger.debug "dias_desde"
      @facturas = Profit::Factura.by_dias_vencidos dias_desde, dias_hasta, co_lin, co_ven, co_zon
    elsif giros_vencidos_desde.to_i > 0 and giros_vencidos_hasta.to_i > 0
      logger.debug "plazo_pago"
      @facturas = Profit::Factura.by_giros_vencidos giros_vencidos_desde, giros_vencidos_hasta, co_lin, co_ven, co_zon
    elsif !@ven_desde.empty? and !@ven_hasta.empty?
      logger.debug "ven_desde"
      @facturas = Profit::Factura.by_fecha_vencidos @ven_desde, @ven_hasta, co_lin, co_ven, co_zon
    elsif !plazo_pago.empty?
      logger.debug "plazo_pago"
      @facturas = Profit::Factura.by_plazo_pago plazo_pago
    elsif !telefono.empty?
      logger.debug "telefonos"
      clientes = Ventas::Cliente.by_telefono telefono
      co_clis = clientes.map{|c| c.ci.to_s }
      logger.debug co_clis.to_s
      @facturas = Profit::Factura.by_clientes co_clis
    else
      @facturas = nil
    end
    
    combos

    respond_to do |format|
      format.html { 
        if params[:commit] == "Buscar"
          render :index 
        else
          render :sms
        end
      }
      format.xls { render :index }
    end    
    
  end

  def update
    if !params[:update][:ci].empty?
      ventas_cliente = Ventas::Cliente.find_by_ci params[:update][:ci]
    else 
      ventas_cliente = Ventas::Cliente.new
    end

    if !params[:update][:co_cli].empty?
      profit_cliente = Profit::Cliente.find_by_co_cli params[:update][:co_cli]
    else 
      profit_cliente = Profit::Cliente.new
    end

    profit_cliente.direc1 = params[:update][:dir1] + " / " + params[:update][:dir2] unless params[:update][:dir1].empty?
    profit_cliente.telefonos = params[:update][:tel1] + " / " + params[:update][:tel2] + " / " + params[:update][:tel3] unless params[:update][:dir1].empty?

    profit_cliente.save

    if ventas_cliente.new_record?
      ventas_cliente = profit_cliente.crear_ventas_cliente
    end

    ventas_cliente.direccion = params[:update][:dir1] unless params[:update][:dir1].empty?
    ventas_cliente.direccion2 = params[:update][:dir2] unless params[:update][:dir2].empty?
    ventas_cliente.telefono = params[:update][:tel1] unless params[:update][:tel1].empty?
    ventas_cliente.telefono2 = params[:update][:tel2] unless params[:update][:tel2].empty?
    ventas_cliente.telefono3 = params[:update][:tel3] unless params[:update][:tel3].empty?

    ventas_cliente.save

    render :text => "alert('Cliente Actualizado')",
         :content_type => "text/javascript"
  end

  def historico
    @cobros = []
    @cobros = Profit::Cobro.historial_by_f params[:fac_num] if params[:fac_num]
    @cobros = Profit::Cobro.historial_by_c params[:co_cli] if params[:co_cli]
    
    @cliente = nil
    @cliente = @cobros[0].cliente unless @cobros.empty?
  end

  def experiencias

    @facturas = Profit::Factura.all_facturas.includes(:cliente) if request.format == "text/plain"

    respond_to do |format|
      format.html { render :experiencias }
      format.txt { render :experiencias }
    end   
  end

  def cuenta
    @cliente = Profit::Cliente.find_by_co_cli params[:co_cli]

    render "cuenta/show"
  end

  def send_sms
    if !params[:profit_factura][:fact_num].empty?
      msj = params[:profit_factura][:fact_num]
      facturas = params[:profit_factura][:factu]
      @msj_enviados_count = 0
      @msj_no_enviados_count = 0
      @msj_error_count = 0
      facturas.each do |f|
        if es_celular_valido?(f[1]["telefono1"])      
          if agendar_sms(msj,f[1]["telefono1"])
            @msj_enviados_count += 1
          else
            @msj_error_count += 1
          end
        elsif es_celular_valido?(f[1]["telefono2"])
          if agendar_sms(msj,f[1]["telefono2"])
            @msj_enviados_count += 1
          else
            @msj_error_count += 1
          end
        else
          @msj_no_enviados_count += 1
        end
      end
    else
      redirect_to :index
    end
  end


  private
  
  def combos
    @lineas = Profit::LinArt.all
    @vendedores = Profit::Vendedor.all
    @zonas = Profit::Zona.all
  end

  def es_celular_valido?(tlf)
    tlf.start_with?("0424", "0414", "0416", "0426", "0412") && tlf.length == 11
  end

  def agendar_sms(msj, tlf)
    begin
      Sms::Outbox.create(:number => tlf, :text => msj, :insertdate => DateTime.now, :fec_venc => DateTime.new)
      true
    rescue
      false
    end
  end

end

app/helpers/cobranzas_helper.rb
module CobranzasHelper
end

app/views/cobranzas/experiencias.html.erb
<h1>Generar Experiencias</h1>

<%= button_to "Generar Experiencias", experiencias_cobranzas_path(:txt) %>

app/views/cobranzas/experiencias.txt.erb
<% logger.debug "Total Facturas " + @facturas.length.to_s  %>
<% @facturas.each_with_index do |f,i| %>
<% f.generar_resumen Time.new %>
<%= f.co_cli.strip + "\t" + f.cliente.cli_des.strip + "\t" + f.cliente.telefonos.strip + "\t" + "\t" + f.fact_num.to_s + "\t" + f.fec_emis.to_date.to_s + "\t" + f.monto_total.to_s + "\t" + f.pago_mensual.to_s + "\t" + f.count_giros.to_s + "\t" + (f.cancelado? ? f.fecha_cancelacion.to_s : "") + "\t" + f.experiencia.to_s %>
<% f = nil %>
<% logger.debug "Procesando " + i.to_s  %>
<% GC.start if (i % 1000) == 0 %>
<% end %>
<% 

    # string Cad = dt.Rows[i]["Cedula"].ToString() + Tab +
    #                     dt.Rows[i]["Nombre"].ToString() + Tab +
    #                     Tab +
    #                     dt.Rows[i]["Telefono"].ToString() + Tab +
    #                     Tab +
    #                     Tab +
    #                     dt.Rows[i]["Factura"].ToString() + Tab +
    #                     FechaE.ToString("dd/MM/yyyy") + Tab +
    #                     MontoT.ToString("#,##0.00;($#,##0.00);0") + Tab +
    #                     Mensual.ToString("#,##0.00;($#,##0.00);0") + Tab +
    #                     dt.Rows[i]["Giros"].ToString() + Tab +
    #                     FechaV.ToString("dd/MM/yyyy") + Tab +
    #                     dt.Rows[i]["Experiencia"].ToString() + Tab;

 %>

app/views/cobranzas/historico.html.erb
<h2>Historial de Pago</h2>
<div class="container">
  <div class="row span7">

      <%= form_for Profit::Cliente.new, :url => historico_cobranzas_path, :method => 'get' do |f| %>

        <div class="control-group">
          <%= label_tag :cliente, nil, :class => 'control-label' %>
          <div class="controls">
            <%= text_field nil, :co_cli, :class => 'input-medium search-query' %>
          </div>
        </div>          
        
        <%= submit_tag "Buscar", :class => 'bnt' %>
        
      <% end %>        
      <div class="control-group">
         <strong><%= label_tag "cedula", "Cedula", :class => 'control-label' %></strong> 
        <div class="controls">
          <%= label_tag "co_cli", @cliente.co_cli, :class => 'control-label' unless @cliente.nil? %>
        </div>
      </div>          
      <div class="control-group">
        <strong><%= label_tag "nombre", "Nombre", :class => 'control-label' %></strong>
        <div class="controls">
          <%= label_tag "cli_des", @cliente.cli_des, :class => 'control-label'  unless @cliente.nil? %>
        </div>
      </div>
      <%= button_tag "Cerrar", :onclick => "javascript:alert('cerrando')", :class => 'bnt' %>
  </div>
  <div class="row" style="font-size:12px">
    <div class="span7" data-toggle="modal-gallery" data-target="#modal-gallery">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Nro. Pago</th>
            <th>Fecha</th>
            <th>Monto</th>
            <th>Detalle</th>
          </tr>
        </thead>
        <tbody>
          <% unless @cobros.nil? %>
            <% @cobros.each do |cobro| %>
                <tr>
                  <td> <%= cobro.cob_num %> </td>  
                  <td> <%= cobro.fec_cob.to_date %> </td>
                  <td> <strong><%= cobro.monto.to_f %></strong>  </td>
                  <td> 
                    <% cobro.reng_cob.each do |reng| %>
                      <p> <%= reng.docum_cc.last.observa + ". Monto: " + reng.neto.to_s  unless reng.docum_cc.empty? %> </p>
                    <% end %>
                  </td>
                </tr>
            <% end %>
          <% end %>
        </tbody>
      </table>
    </div>

  </div>
</div>

app/views/cobranzas/index.html.erb
<h2>Gestión de Cobranzas</h2>
<div class="container">
  <div class="row span6">
    <%= form_for @factura, :url => show_cobranzas_path do |f| %>
      <div class="row">
        <div class="span3">
          <div class="control-group">
            <%= f.label :co_cli, :class => 'control-label' %>
            <div class="controls">
              <%= f.text_field :co_cli, :class => 'input-small', :value => params[:profit_factura].nil? ? "" : params[:profit_factura][:co_cli] %>
            </div>
          </div>
          <div class="control-group">
            <%= label_tag :dias_vencidos_desde, nil, :class => 'control-label' %>
            <div class="controls">
              <%= number_field_tag :dias_vencidos_desde, params[:dias_vencidos_desde].nil? ? "0" : params[:dias_vencidos_desde], :class => 'input-small', :step => 30  %>
            </div>
            <div class="controls">
              <%= number_field_tag :dias_vencidos_hasta, params[:dias_vencidos_hasta].nil? ? "0" : params[:dias_vencidos_hasta], :class => 'input-small', :step => 30  %>
            </div>
          </div>          
          <div class="control-group">
            <%= label_tag :giros_vencidos, nil, :class => 'control-label' %>
            <div class="controls">
              <%= number_field_tag :giros_vencidos_desde, params[:giros_vencidos_desde].nil? ? "0" : params[:giros_vencidos_desde], :class => 'input-small' %>
            </div>
            <div class="controls">
              <%= number_field_tag :giros_vencidos_hasta, params[:giros_vencidos_hasta].nil? ? "0" : params[:giros_vencidos_hasta], :class => 'input-small' %>
            </div>
          </div>          
          <div class="control-group">
            <%= label_tag :vencidos_desde, nil, :class => 'control-label' %>
            <div class="controls">
              <%= text_field :vencidos_desde, nil, :class => 'input-small', "data-behaviour" => 'datepicker' %>
            </div>
            <div class="controls">
              <%= text_field :vencidos_hasta, nil, :class => 'input-small', "data-behaviour" => 'datepicker' %>
            </div>
          </div>          
          <div class="control-group">
            <%= label_tag :plazo_pago, nil, :class => 'control-label' %>
            <div class="controls">
              <%= text_field :plazo_pago, "", :class => 'input-small', "data-behaviour" => 'datepicker', :value => (params[:plazo_pago].nil? ? "" : params[:plazo_pago][0]) %>
            </div>
          </div>          
        </div>
        <div class="span3">
          <div class="control-group">
            <%= label_tag :lineas, nil, :class => 'control-label' %>
            <div class="controls">
              <%= select_tag :co_lin, options_from_collection_for_select(@lineas, "co_lin", "lin_des", params[:co_lin].nil? ? "" : params[:co_lin]), :prompt => "", :class => 'input-medium' %>
            </div>
          </div>          
          <div class="control-group">
            <%= label_tag :vendedores, nil, :class => 'control-label' %>
            <div class="controls">
              <%= select_tag :co_ven, options_from_collection_for_select(@vendedores, "co_ven", "ven_des", params[:co_ven].nil? ? "" : params[:co_ven]), :prompt => "", :class => 'input-medium' %>
            </div>
          </div>          
          <div class="control-group">
            <%= label_tag :zonas, nil, :class => 'control-label' %>
            <div class="controls">
              <%= select_tag :co_zon, options_from_collection_for_select(@zonas, "co_zon", "zon_des", params[:co_zon].nil? ? "" : params[:co_zon]), :prompt => "", :class => 'input-medium' %>
            </div>
          </div>
          <div class="control-group">
            <%= label_tag :telefono, nil, :class => 'control-label' %>
            <div class="controls">
              <%= text_field :telefono, "", :class => 'input-medium', :value => (params[:telefono].nil? ? "" : params[:telefono][0]) %>
            </div>
          </div>          
          <div class="control-group">
            <%= label_tag :sin_seguimientos_recientes, nil, :class => 'control-label' %>
            <div class="controls">
              <%= check_box_tag :recientes, "1", params[:recientes].nil? ? false : true %>
            </div>
          </div>
          <div class="control-group">
            <%= label_tag :sin_pagos_recientes, nil, :class => 'control-label' %>
            <div class="controls">
              <%= check_box_tag :sin_pagos_recientes, "1", params[:sin_pagos_recientes].nil? ? false : true %>
            </div>
          </div>
    
          <%= submit_tag "Buscar", :class => 'bnt',:id => 'btn_html' %>
          <br><br>
          <%= submit_tag 'Exportar XLS', :class => 'bnt', :id => 'btn_xls' %>
          <br><br>
          <%= submit_tag 'Enviar SMS', :class => 'bnt', :id => 'btn_xls' %>

        </div>
      </div>


    <% end %>    
  </div>
  <div class="row" style="font-size:12px">
    <div class="span7" data-toggle="modal-gallery" data-target="#modal-gallery">
      <table id="tfacturas" class="table table-striped tablesorter">
        <thead>
          <tr>
            <th></th>
            <th>Cédula <i style="color:transparent" class="icon-resize-vertical"></i> </th>
            <th>Nombre <i style="color:transparent" class="icon-resize-vertical"></i></th>
            <th data-sorter="false">Teléfonos</th>
            <th data-sorter="false">Dirección</th>
            <th data-sorter="false"></th>
            <th>Nro. Factura <i style="color:transparent" class="icon-resize-vertical"></i> </th>
            <th>Fecha de Compra <i style="color:transparent" class="icon-resize-vertical"></i> </th>
            <th>Ultima Fecha Pago <i style="color:transparent" class="icon-resize-vertical"></i> </th>
            <th>Días sin cancelar <i style="color:transparent" class="icon-resize-vertical"></i> </th>
            <th>Giros Vencídos <i style="color:transparent" class="icon-resize-vertical"></i> </th>
            <th>Monto Vencído <i style="color:transparent" class="icon-resize-vertical"></i> </th>
            <th data-sorter="false">Experiencia</th>
            <th>Vendedora <i style="color:transparent" class="icon-resize-vertical"></i> </th>
            <th>Zona <i style="color:transparent" class="icon-resize-vertical"></i> </th>
            <th data-sorter="false">Acciones</th>
          </tr>
        </thead>
        <tbody>
          <% unless @facturas.nil? %>
            <% @facturas.each do |factu| %>
              <% factu.generar_resumen Time.now %>
              <% unless factu.cancelado? or (@sin_seguimientos_recientes and factu.atendido_recientemente?(10)) or (@sin_pagos_recientes and (factu.ultimo_pago_entre?(@ven_desde,@ven_hasta))) %>
                
                <tr id="<%= factu.fact_num %>">
                  <%= form_for factu, :url => update_cobranzas_path, :remote => true do |f| %>
                  <td> <a style="color:transparent" id="" href="javascript:$('#<%= factu.fact_num %>').remove();$('#tfacturas').trigger('updateAll');"><i class="icon-remove-circle"></i></a>  </td>
                  <td> 
                    <%= factu.cliente.co_cli %> <br>
                    <p> <%= link_to "Ficha", ventas_cliente_path(factu.cliente_venta), :class => "btn btn-mini btn-info", :target => '_blank' unless factu.cliente_venta.nil? %> </p>
                    <%= hidden_field :update, :ci, :value => factu.cliente_venta.nil? ? "" : factu.cliente_venta.ci.to_s  %>
                    <%= hidden_field :update, :co_cli, :value => factu.cliente.nil? ? "" : factu.cliente.co_cli  %>
                  </td>  
                  <td> <%= factu.cliente.cli_des %> </td>
                  <td> 
                    <%= text_field :update, :tel1, :class => 'input-small', :value => factu.cliente_venta.nil? ? "" : factu.cliente_venta.telefono  %> <br>
                    <%= text_field :update, :tel2, :class => 'input-small', :value => factu.cliente_venta.nil? ? "" : factu.cliente_venta.telefono2 %> 
                    <%= text_field :update, :tel3, :class => 'input-small', :value => factu.cliente_venta.nil? ? "" : factu.cliente_venta.telefono3 %> 
                  </td>
                  <td> 
                    <%= text_area :update, :dir1, :cols => 30, :rows => 2, :class => 'input-large', :value => factu.cliente_venta.nil? ? "" : factu.cliente_venta.direccion %> <br>
                    <%= text_area :update, :dir2, :cols => 30, :rows => 2, :class => 'input-large', :value => factu.cliente_venta.nil? ? "" : factu.cliente_venta.direccion2 %> 
                  </td>
                  <td> 
                    <p><%= submit_tag "Actualizar", :class => 'btn btn-mini btn-primary', :id => "btn_update" %></p>
                  </td>
                  <td> <%= factu.fact_num %> </td>
                  <td> <%= factu.fec_emis.to_date %> </td>
                  <td class="span2"> 
                    <%= factu.fecha_ultimo_pago.to_date unless factu.fecha_ultimo_pago.nil? %> 
                    <p> <%= link_to "Pagos", historico_cobranzas_by_factura_path(factu), :class => "btn btn-mini btn-info", :target => '_blank' %> </p>
                  </td>
                  <td> <%= factu.dias_desde_ultimo_pago %> </td>
                  <td> <%= factu.giros_vencidos_sin_cancelar %> </td>
                  <td> <%= factu.saldo_vencido_sin_cancelar.round 2 %> 
                    <p> <%= link_to "Cuenta", cuenta_cobranzas_path(factu.cliente), :class => "btn btn-mini btn-info", :target => '_blank' %> </p>
                  </td>
                  <td> 
                    <%= factu.experiencia %> 
                    <p> <%= link_to "Seguimientos", ventas_seguimientos_path + "?ventas_seguimiento%5Bcliente_id%5D=#{factu.cliente.co_cli}", :class => "btn btn-mini btn-success", :target => '_blank' %> </p>
                  </td>
                  <td> <%= factu.vendedor.ven_des %> </td>
                  <td> <%= factu.cliente.zona.zon_des %> </td>
                  <td> 
                    <p> <%= link_to "Nuevo Seguimiento", new_ventas_seguimiento_path + "?ventas_seguimiento%5Bcliente_id%5D=#{factu.cliente.co_cli}", :class => "btn btn-mini btn-inverse", :target => '_blank' %> </p>
                  </td>
                  <% end %>
                </tr>
              <% end %>
            <% end %>
          <% end %>
        </tbody>
      </table>
      <div id="pager" class="pager">
        <form>
          <img src="/img/first.png" class="first"/>
          <img src="/img/prev.png" class="prev"/>
          <span class="pagedisplay"></span> <!-- this can be any element, including an input -->
          <img src="/img/next.png" class="next"/>
          <img src="/img/last.png" class="last"/>        
        </form>
      </div>    

    </div>
  </div>
</div>

app/views/cobranzas/send_sms.html.erb
<h1>Mensajes enviados</h1>

<h3><%= @msj_enviados_count %> Mensajes fueron agendados para ser enviados</h3>
<h3><%= @msj_no_enviados_count %> Mensajes no fueron enviados debido a que el numero no es adecuado</h3>
<h3><%= @msj_error_count %> Mensajes presentaron errores al intentar ser enviados</h3>

<%= link_to "Culminar", cobranzas_path  %>