config/routes.rb
Arv2::Application.routes.draw do
  resources :feriados

  resources :goals

  resources :parroquia

  resources :municipios

  resources :estados

  devise_for :users, :controllers => { :passwords => "users/passwords", :sessions => "users/sessions" }
  scope "/admin" do
    resources :users
  end  

  namespace :ventas do 
    resources :seguimientos
  end

  namespace :ventas do 
    resources :presupuestos do
      collection do
        get 'clientes'
        get 'productos'
        get "print/:id" => 'presupuestos#printing', :as => :print
        get "convenio/:id" => 'presupuestos#convenio', :as => :convenio        
      end
    end
  end

  namespace :ventas do 
    resources :clientes do
      collection do
        get "migrate"
        get "print/:id" => 'clientes#printing', :as => :print
      end
    end 
  end

  root :to => 'home#index'

  get "/intranet" => 'intranet#index', :as => :intranet

  get "/cuenta" => 'cuenta#index', :as => :cuenta
  post "/cuenta/show" => 'cuenta#show', :as => :show_cuenta

  get "/informe" => 'informe#index', :as => :informe
  post "/informe/show" => 'informe#show', :as => :show_informe

  get "/productos" => 'productos#index', :as => :productos
  post "/productos/show" => 'productos#show', :as => :show_productos

  get "/garantia" => 'garantia#index', :as => :garantia
  post "/garantia/show" => 'garantia#show', :as => :show_garantia

  match '/historia', :to => 'historia#index'
  match '/contacto', :to => 'contacto#index'  

  match '/servicios', :to => 'servicios#index'

  get "/cobranzas" => 'cobranzas#index', :as => :cobranzas
  get "/cobranzas/historico/:fac_num" => 'cobranzas#historico', :as => :historico_cobranzas_by_factura
  get "/cobranzas/historico" => 'cobranzas#historico', :as => :historico_cobranzas
  post "/cobranzas/show" => 'cobranzas#show', :as => :show_cobranzas
  post "/cobranzas/send_sms" => 'cobranzas#send_sms', :as => :send_sms_cobranzas
  post "/cobranzas/update" => 'cobranzas#update', :as => :update_cobranzas
  get "/cobranzas/experiencias" => 'cobranzas#experiencias', :as => :experiencias_cobranzas
  post "/cobranzas/experiencias" => 'cobranzas#experiencias', :as => :experiencias_cobranzas
  get "/cobranzas/cuenta/:co_cli" => 'cobranzas#cuenta', :as => :cuenta_cobranzas

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
  
end

app/models/cobranza.rb
module Cobranza
  def self.table_name_prefix
    ''
  end
end

app/models/estado.rb
class Estado < ActiveRecord::Base
  has_many :municipio
  attr_accessible :descripcion
end

app/models/feriado.rb
class Feriado < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  attr_accessible :month, :sales, :billing
end

app/models/municipio.rb
class Municipio < ActiveRecord::Base

  belongs_to :estado
  has_many :parroquias

  attr_accessible :descripcion, :estado_id
end

app/models/parroquia.rb
class Parroquia < ActiveRecord::Base

  belongs_to :municipio
  belongs_to :cliente, {:class_name => "Ventas::Cliente"}
  attr_accessible :descripcion, :municipio_id
end

app/models/profit.rb
module Profit
  def self.table_name_prefix
    ''
  end
end

app/models/role.rb
class Role < ActiveRecord::Base

  has_many :users
  attr_accessible :name

end

app/models/servicios.rb
module Servicios
  def self.table_name_prefix
    ''
  end
end

app/models/sms.rb
module Sms
  def self.table_name_prefix
    ''
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :role

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :name, :profit
  # attr_accessible :title, :body

  def to_string
    self.username + " - " + self.name
  end

end

app/models/ventas.rb
module Ventas
  def self.table_name_prefix
    ''
  end
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  def index
    @producto = Profit::Art.new
    @producto.art_des = ''
    @productos = nil
  end

  def show
    @producto = Profit::Art.new
    @producto.art_des = ''    
    @productos = Profit::Art.where('art_des like ? or co_art like ? or modelo like ?',"%#{params[:profit_art][:art_des]}%","%#{params[:profit_art][:art_des]}%","%#{params[:profit_art][:art_des]}%") 
    render :index
  end
end

app/helpers/contacto_helper.rb
module ContactoHelper
end

app/helpers/cuenta_helper.rb
module CuentaHelper
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/helpers/feriados_helper.rb
module FeriadosHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/informe_helper.rb
module InformeHelper
  def select_month_tag
    begining = "2013-01-01".to_date

    #select_tag :mes
    select_month(Date.today)
  end

  def select_year_tag
    begining = "2013-01-01".to_date

    #select_tag :mes
    select_year(Date.today, :start_year => Date.today.year - 3, :end_year => Date.today.year)
  end

end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/productos/index.html.erb
<h2>Consulta de Productos</h2>
<div class="container offset1">
  <div class="row span7 offset2">
    <%= form_for @producto, :url => show_productos_path do |f| %>
      <%= f.text_field :art_des, :class => 'input-medium search-query' %>
      <%= submit_tag "Buscar", :class => 'bnt' %>
    <% end %>    
  </div>
  <div class="row">
    <div class="span7" data-toggle="modal-gallery" data-target="#modal-gallery">
      <table class="table table-striped">
        <thead>
          <tr>
            <th>Foto</th>
            <th>Codigo</th>
            <th>Descripción</th>
            <th>Modelo</th>
            <th>¿En Existencia?</th>
          </tr>
        </thead>
        <tbody>

          <% unless @productos.nil? %>
            <% @productos.each do |p| %>
            <tr>
              <td>
                <a href="<%= p.url_photo %>" title="<%= p.art_des.encode("UTF-8") %>" data-gallery="gallery">
                  <%= image_tag p.url_small_photo %>
                </a>              
              </td>
              <td><%= p.co_art %></td>
              <td><%= p.art_des %></td>
              <td><%= p.modelo %></td>
              <td>
                <% if p.stock_act > 0.0 %>
                  <span class="label label-success">Sí</span>
                <% else %>
                  <span class="label label-important">No</span>
                <% end %>
              </td>
            </tr>
            <% end %>
          <% end %>            
        </tbody>
      </table>
    </div>

  </div>
</div>

<!-- modal-gallery is the modal dialog used for the image gallery -->
<div id="modal-gallery" class="modal modal-gallery hide fade" tabindex="-1">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">&times;</a>
        <h3 class="modal-title"></h3>
    </div>
    <div class="modal-body"><div class="modal-image"></div></div>
    <div class="modal-footer">
        <a class="btn btn-primary" data-dismiss="modal">Cerrar</a>
    </div>
</div>