config/routes.rb
Arv2::Application.routes.draw do
  resources :feriados

  resources :goals

  resources :parroquia

  resources :municipios

  resources :estados

  devise_for :users, :controllers => { :passwords => "users/passwords", :sessions => "users/sessions" }
  scope "/admin" do
    resources :users
  end  

  namespace :ventas do 
    resources :seguimientos
  end

  namespace :ventas do 
    resources :presupuestos do
      collection do
        get 'clientes'
        get 'productos'
        get "print/:id" => 'presupuestos#printing', :as => :print
        get "convenio/:id" => 'presupuestos#convenio', :as => :convenio        
      end
    end
  end

  namespace :ventas do 
    resources :clientes do
      collection do
        get "migrate"
        get "print/:id" => 'clientes#printing', :as => :print
      end
    end 
  end

  root :to => 'home#index'

  get "/intranet" => 'intranet#index', :as => :intranet

  get "/cuenta" => 'cuenta#index', :as => :cuenta
  post "/cuenta/show" => 'cuenta#show', :as => :show_cuenta

  get "/informe" => 'informe#index', :as => :informe
  post "/informe/show" => 'informe#show', :as => :show_informe

  get "/productos" => 'productos#index', :as => :productos
  post "/productos/show" => 'productos#show', :as => :show_productos

  get "/garantia" => 'garantia#index', :as => :garantia
  post "/garantia/show" => 'garantia#show', :as => :show_garantia

  match '/historia', :to => 'historia#index'
  match '/contacto', :to => 'contacto#index'  

  match '/servicios', :to => 'servicios#index'

  get "/cobranzas" => 'cobranzas#index', :as => :cobranzas
  get "/cobranzas/historico/:fac_num" => 'cobranzas#historico', :as => :historico_cobranzas_by_factura
  get "/cobranzas/historico" => 'cobranzas#historico', :as => :historico_cobranzas
  post "/cobranzas/show" => 'cobranzas#show', :as => :show_cobranzas
  post "/cobranzas/send_sms" => 'cobranzas#send_sms', :as => :send_sms_cobranzas
  post "/cobranzas/update" => 'cobranzas#update', :as => :update_cobranzas
  get "/cobranzas/experiencias" => 'cobranzas#experiencias', :as => :experiencias_cobranzas
  post "/cobranzas/experiencias" => 'cobranzas#experiencias', :as => :experiencias_cobranzas
  get "/cobranzas/cuenta/:co_cli" => 'cobranzas#cuenta', :as => :cuenta_cobranzas

  # See how all your routes lay out with "rake routes"

  # This is a legacy wild controller route that's not recommended for RESTful applications.
  # Note: This route will make all actions in every controller accessible via GET requests.
  # match ':controller(/:action(/:id))(.:format)'
  
end

app/models/cobranza.rb
module Cobranza
  def self.table_name_prefix
    ''
  end
end

app/models/estado.rb
class Estado < ActiveRecord::Base
  has_many :municipio
  attr_accessible :descripcion
end

app/models/feriado.rb
class Feriado < ActiveRecord::Base
  # attr_accessible :title, :body
end

app/models/goal.rb
class Goal < ActiveRecord::Base
  attr_accessible :month, :sales, :billing
end

app/models/municipio.rb
class Municipio < ActiveRecord::Base

  belongs_to :estado
  has_many :parroquias

  attr_accessible :descripcion, :estado_id
end

app/models/parroquia.rb
class Parroquia < ActiveRecord::Base

  belongs_to :municipio
  belongs_to :cliente, {:class_name => "Ventas::Cliente"}
  attr_accessible :descripcion, :municipio_id
end

app/models/profit.rb
module Profit
  def self.table_name_prefix
    ''
  end
end

app/models/role.rb
class Role < ActiveRecord::Base

  has_many :users
  attr_accessible :name

end

app/models/servicios.rb
module Servicios
  def self.table_name_prefix
    ''
  end
end

app/models/sms.rb
module Sms
  def self.table_name_prefix
    ''
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  belongs_to :role

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :username, :name, :profit
  # attr_accessible :title, :body

  def to_string
    self.username + " - " + self.name
  end

end

app/models/ventas.rb
module Ventas
  def self.table_name_prefix
    ''
  end
end

app/controllers/estados_controller.rb
class EstadosController < ApplicationController
  layout 'intranet'
  before_filter :authenticate_user!

  # GET /estados
  # GET /estados.json
  def index
    @estados = Estado.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @estados }
    end
  end

  # GET /estados/1
  # GET /estados/1.json
  def show
    @estado = Estado.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @estado }
    end
  end

  # GET /estados/new
  # GET /estados/new.json
  def new
    @estado = Estado.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @estado }
    end
  end

  # GET /estados/1/edit
  def edit
    @estado = Estado.find(params[:id])
  end

  # POST /estados
  # POST /estados.json
  def create
    @estado = Estado.new(params[:estado])

    respond_to do |format|
      if @estado.save
        format.html { redirect_to @estado, notice: 'Estado was successfully created.' }
        format.json { render json: @estado, status: :created, location: @estado }
      else
        format.html { render action: "new" }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /estados/1
  # PUT /estados/1.json
  def update
    @estado = Estado.find(params[:id])

    respond_to do |format|
      if @estado.update_attributes(params[:estado])
        format.html { redirect_to @estado, notice: 'Estado was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @estado.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /estados/1
  # DELETE /estados/1.json
  def destroy
    @estado = Estado.find(params[:id])
    @estado.destroy

    respond_to do |format|
      format.html { redirect_to estados_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/contacto_helper.rb
module ContactoHelper
end

app/helpers/cuenta_helper.rb
module CuentaHelper
end

app/helpers/estados_helper.rb
module EstadosHelper
end

app/helpers/feriados_helper.rb
module FeriadosHelper
end

app/helpers/garantia_helper.rb
module GarantiaHelper
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/historia_helper.rb
module HistoriaHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/informe_helper.rb
module InformeHelper
  def select_month_tag
    begining = "2013-01-01".to_date

    #select_tag :mes
    select_month(Date.today)
  end

  def select_year_tag
    begining = "2013-01-01".to_date

    #select_tag :mes
    select_year(Date.today, :start_year => Date.today.year - 3, :end_year => Date.today.year)
  end

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/estados/_form.html.erb
<%= form_for @estado, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :descripcion, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :descripcion, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                estados_path, :class => 'btn' %>
  </div>
<% end %>

app/views/estados/edit.html.erb
<%- model_class = Estado -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/estados/index.html.erb
<%- model_class = Estado -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:descripcion) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @estados.each do |estado| %>
      <tr>
        <td><%= link_to estado.id, estado_path(estado) %></td>
        <td><%= estado.descripcion %></td>
        <td><%=l estado.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_estado_path(estado), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      estado_path(estado),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_estado_path,
            :class => 'btn btn-primary' %>

app/views/estados/new.html.erb
<%- model_class = Estado -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/estados/show.html.erb
<%- model_class = Estado -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:descripcion) %>:</strong></dt>
  <dd><%= @estado.descripcion %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              estados_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_estado_path(@estado), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              estado_path(@estado),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>